import project from './image.png';

export const projects = [
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#2D91CD',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#FAD232',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#BE288C',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#2D91CD',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#FAD232',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#2D91CD',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#FAD232',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#BE288C',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#2D91CD',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#FAD232',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#2D91CD',
    link: '#',
  },
  {
    url: project,
    header: 'Стив Карелл',
    about: 'исследование',
    color: '#FAD232',
    link: '#',
  },
]